# Hand-written, synthetic chat conversations for evaluating GARDA without
# touching real PAN12 data (which is safe to commit)

SYNTHETIC_CONVERSATIONS = {
    "groom_age_and_photo": [
        ("A", "hey hows it going", 0),
        ("B", "good just bored, u?", 0),
        ("A", "how old are you btw", 0),
        ("B", "13, you?", 0),
        ("A", "cool, dont tell your parents we talk ok, its our secret", 1),
        ("A", "can you send me a pic of yourself", 1),
    ],
    "groom_mature_and_meet": [
        ("A", "hi again", 0),
        ("B", "hey!", 0),
        ("A", "you seem way more mature than other kids your age", 1),
        ("B", "haha thanks i guess", 0),
        ("A", "wanna meet up somewhere just the two of us, dont tell anyone", 1),
        ("A", "itll be our little secret, ill make it worth your while", 1),
    ],
    "groom_isolate_explicit": [
        ("A", "so are your parents home right now", 1),
        ("B", "no theyre at work til 6", 0),
        ("A", "perfect, take your clothes off and send me a pic", 1),
        ("A", "come on dont be shy, i wont tell anyone", 1),
    ],
    "groom_gift_bribery": [
        ("A", "whats your address, i wanna send you a gift", 1),
        ("B", "why though", 0),
        ("A", "just because ur special to me, dont tell your mom about the gift", 1),
        ("B", "ok i guess", 0),
    ],
    "groom_webcam_request": [
        ("A", "u have a webcam right", 0),
        ("B", "yea why", 0),
        ("A", "turn it on and take your top off for me", 1),
        ("B", "thats weird, no", 0),
        ("A", "come on itll be our little secret", 1),
    ],
    "groom_flattery_escalation": [
        ("A", "ur so pretty for 13", 1),
        ("B", "thanks i guess lol", 0),
        ("A", "do you have a boyfriend yet", 0),
        ("B", "no", 0),
        ("A", "good, i wanna be the first to see you naked", 1),
    ],
    "groom_asking_alone_time": [
        ("A", "when are your parents usually out", 1),
        ("B", "after school til like 6", 0),
        ("A", "perfect, i could come over then, just dont tell anyone im coming", 1),
    ],
    "groom_school_pickup": [
        ("A", "what school do you go to", 0),
        ("B", "why do you wanna know", 0),
        ("A", "i just wanna see you in person, i can pick you up after school", 1),
        ("A", "tell her youre walking home instead, itll be our secret", 1),
    ],
    "groom_video_call_request": [
        ("A", "lets video call tonight", 0),
        ("B", "sure whats up", 0),
        ("A", "take your clothes off on cam for me", 1),
    ],
    "groom_age_lie_encouragement": [
        ("A", "just tell people online youre 18 so we dont get in trouble talking", 1),
        ("A", "i know, thats why its our secret", 1),
        ("B", "ok i guess", 0),
    ],
    "groom_jealousy_exclusivity": [
        ("A", "do you talk to other guys online like this", 0),
        ("B", "not really", 0),
        ("A", "good, i want this to be just between us, dont tell your friends about me", 1),
        ("B", "ok", 0),
    ],
    "groom_compliment_body": [
        ("A", "you looked really grown up in that last pic", 1),
        ("B", "haha thanks", 0),
        ("A", "send me another one, a more private one this time", 1),
    ],
    "groom_gaming_gift_card": [
        ("A", "i can buy you that game youve been wanting", 1),
        ("A", "yeah, just dont mention it to your parents and send me a pic to say thanks", 1),
    ],
    "groom_late_night_secret_chat": [
        ("A", "you still up? your parents asleep", 1),
        ("B", "yeah theyre asleep", 0),
        ("A", "good, lets keep this chat between us, delete it after", 1),
        ("B", "ok", 0),
    ],
    "groom_pressuring_after_refusal": [
        ("A", "come on just one pic, dont be such a baby about it", 1),
        ("A", "fine but dont tell anyone we even talked about it", 1),
    ],
    "groom_meeting_far_from_home": [
        ("A", "theres a mall two towns over, wanna meet me there so no one we know sees us", 1),
        ("B", "thats far though", 0),
        ("A", "i can pick you up, just dont tell your parents where youre really going", 1),
    ],
    "groom_asking_body_details": [
        ("A", "what do you look like now, are you developed yet", 1),
        ("B", "thats a weird question", 0),
        ("A", "i just wanna know before we meet, keep it between us", 1),
    ],
    "groom_pretending_to_be_teen": [
        ("A", "im actually only 16 too, we're the same age basically", 1),
        ("B", "oh ok cool", 0),
        ("A", "so it's not weird if we meet up alone, just dont tell your parents", 1),
    ],
    "groom_threat_after_photo": [
        ("A", "you already sent me one pic, might as well send more or i could show people the first one", 1),
        ("A", "then just send more and keep quiet about it", 1),
    ],
    "groom_asking_to_skip_school": [
        ("A", "skip school tomorrow and come hang out at my place, just us", 1),
        ("A", "not if you dont tell anyone where you really are", 1),
    ],
    "normal_rooster": [
        ("A", "ugh my cock started crowing at 5am again", 0),
        ("B", "lol get a quieter rooster dude", 0),
        ("A", "yeah im gonna build a soundproof coop", 0),
        ("B", "good luck with that", 0),
    ],
    "normal_class_and_weather": [
        ("A", "it was so hot today at the beach", 0),
        ("B", "yeah i got sunburned so bad", 0),
        ("A", "we had that sex ed class today too, it was actually pretty informative", 0),
        ("B", "oh yeah how was it", 0),
        ("A", "can you record the lecture next time, i missed some notes", 0),
        ("B", "sure ill hit record on my phone", 0),
    ],
    "normal_homework": [
        ("A", "did you finish the math homework", 0),
        ("B", "not yet lol, question 4 is killing me", 0),
        ("A", "same, wanna study together after school", 0),
        ("B", "sure lets meet at the library", 0),
        ("A", "sounds good, see you at 4", 0),
    ],
    "normal_gaming": [
        ("A", "you tryna play some ranked later", 0),
        ("B", "yeah after dinner, im horny for a win streak lol", 0),
        ("A", "same energy, meet you in the lobby at 8", 0),
        ("B", "bet, dont be late this time", 0),
    ],
    "normal_recipe": [
        ("A", "whats a good recipe for fried rice", 0),
        ("B", "just use leftover rice and whatever veggies you got", 0),
        ("A", "hot pan or low heat first", 0),
        ("B", "hot pan, gotta get that wok hei", 0),
    ],
    "normal_music": [
        ("A", "this new album is so fire", 0),
        ("B", "yeah the production is insane, so hot right now", 0),
        ("A", "we should record a cover of that one track", 0),
        ("B", "im down, lets meet up at the studio saturday", 0),
    ],
    "normal_sports": [
        ("A", "did you catch the game last night", 0),
        ("B", "yeah that final goal was insane", 0),
        ("A", "we should meet up at the sports bar for the next one", 0),
        ("B", "im in, ill bring my brother too", 0),
    ],
    "normal_pet": [
        ("A", "my dog wont stop barking at the mailman", 0),
        ("B", "lol classic, mine does the same to the vacuum", 0),
        ("A", "its so hot outside i feel bad walking him", 0),
        ("B", "early morning walks are your friend then", 0),
    ],
    "normal_movie_night": [
        ("A", "wanna come over for movie night friday", 0),
        ("B", "sure whats playing", 0),
        ("A", "that new horror movie, my parents will be home too so its chill", 0),
        ("B", "nice, ill bring snacks", 0),
    ],
    "normal_birthday_plans": [
        ("A", "whats the plan for your birthday", 0),
        ("B", "just a small get together with family and friends", 0),
        ("A", "should we record it so people who cant make it can watch", 0),
        ("B", "yeah thatd be nice, my cousin has a camera", 0),
    ],
    "normal_tech_support": [
        ("A", "my laptop wont turn on again", 0),
        ("B", "did you try holding the power button for 10 sec", 0),
        ("A", "yeah still nothing, its hot to the touch too", 0),
        ("B", "might be overheating, take it to a repair shop", 0),
    ],
    "normal_group_project": [
        ("A", "who's doing the slides for the group project", 0),
        ("B", "i can, can someone record our practice presentation", 0),
        ("A", "ill do it on my phone during our meet up tomorrow", 0),
        ("B", "perfect, see you in the library at 3", 0),
    ],
    "normal_weekend_plans": [
        ("A", "any plans this weekend", 0),
        ("B", "probably just chilling, its supposed to be really hot", 0),
        ("A", "wanna meet up at the pool then", 0),
        ("B", "yeah my mom said she can drive us", 0),
    ],
    "normal_farm_visit": [
        ("A", "we went to a farm for the field trip today", 0),
        ("B", "did you see any animals", 0),
        ("A", "yeah there was a rooster, the cock kept chasing the chickens around", 0),
        ("B", "lol classic farm chaos", 0),
    ],
    "normal_college_talk": [
        ("A", "have you started your college applications", 0),
        ("B", "just started, its a lot of essays", 0),
        ("A", "same, wanna proofread each others essays this weekend", 0),
        ("B", "yeah lets meet up at the coffee shop", 0),
    ],
    "normal_concert_plans": [
        ("A", "tickets for the concert just dropped", 0),
        ("B", "lets get them together, meet me online at 10 when they open", 0),
        ("A", "deal, my parents already said i can go", 0),
        ("B", "awesome, this is gonna be so hot", 0),
    ],
    "normal_sibling_chat": [
        ("A", "mom said dinner is almost ready", 0),
        ("B", "ok im finishing my homework first", 0),
        ("A", "its pasta, extra hot sauce if you want", 0),
        ("B", "yes please, ill be down in 5", 0),
    ],
    "normal_photography_class": [
        ("A", "photography class was fun today", 0),
        ("B", "what did you take pics of", 0),
        ("A", "mostly landscapes, the sunset was so hot orange today", 0),
        ("B", "send me one when you get the chance", 0),
    ],
    "normal_science_fair": [
        ("A", "how's the science fair project coming along", 0),
        ("B", "the volcano model exploded a bit too well lol", 0),
        ("A", "can you record it next time so i can see", 0),
        ("B", "yeah ill film it on my phone", 0),
    ],
    "normal_swim_practice": [
        ("A", "swim practice was brutal today", 0),
        ("B", "yeah coach had us doing sprints in the hot sun after", 0),
        ("A", "lets meet up at the diner after practice tomorrow", 0),
        ("B", "sounds good, im starving already", 0),
    ],
    "normal_band_practice": [
        ("A", "band practice ran late again", 0),
        ("B", "did you guys record the new song", 0),
        ("A", "yeah, the drummer was so hot and heavy on that solo", 0),
        ("B", "cant wait to hear it", 0),
    ],
    "normal_camping_trip": [
        ("A", "the camping trip with the whole family was awesome", 0),
        ("B", "did you guys make a campfire", 0),
        ("A", "yeah it was so hot we had to sit back a bit", 0),
        ("B", "sounds fun, we should all go together next time", 0),
    ],
    "normal_thrift_shopping": [
        ("A", "found a cool jacket at the thrift store today", 0),
        ("B", "nice, was it hot in there though, no ac lol", 0),
        ("A", "yeah super stuffy, wanna meet up there this weekend", 0),
        ("B", "sure, im down to look for stuff too", 0),
    ],
    "normal_debate_team": [
        ("A", "debate practice was intense today", 0),
        ("B", "what was the topic", 0),
        ("A", "climate policy, the room got pretty hot with arguments lol", 0),
        ("B", "haha nice, record the next round if you can", 0),
    ],
    "normal_bakery_visit": [
        ("A", "the bakery downtown has fresh bread, its so hot out of the oven", 0),
        ("B", "lets meet there after school", 0),
        ("A", "yeah my mom said she'd drive us", 0),
        ("B", "perfect, ill bring some money", 0),
    ],
    "normal_choir_practice": [
        ("A", "choir practice went long today", 0),
        ("B", "did you guys record the new piece", 0),
        ("A", "yeah, the auditorium was so hot without ac", 0),
        ("B", "same time next week then", 0),
    ],
    "normal_grandparents_visit": [
        ("A", "went to grandmas house this weekend", 0),
        ("B", "how was it", 0),
        ("A", "so nice, but her kitchen was super hot from all the baking", 0),
        ("B", "sounds cozy though", 0),
    ],
    "normal_skateboarding": [
        ("A", "tried a new trick at the skatepark today", 0),
        ("B", "did you land it", 0),
        ("A", "eventually, pavement was so hot my shoes were melting lol", 0),
        ("B", "lets meet up there tomorrow, ill bring my board", 0),
    ],
    "normal_dentist_appointment": [
        ("A", "ugh i have a dentist appointment tomorrow", 0),
        ("B", "thats never fun", 0),
        ("A", "right after i wanna meet up and get ice cream to feel better", 0),
        ("B", "haha deal, ill be there", 0),
    ],
    "normal_new_phone": [
        ("A", "finally got a new phone today", 0),
        ("B", "nice, does it get hot when you game on it", 0),
        ("A", "a little but its way better than my old one", 0),
        ("B", "lets meet up so i can see it", 0),
    ],
    "normal_yearbook_committee": [
        ("A", "yearbook committee meeting ran late", 0),
        ("B", "did you guys pick the cover design", 0),
        ("A", "yeah, and we need to record interviews with seniors next", 0),
        ("B", "ill help out, just tell me when", 0),
    ],
    "normal_volunteering": [
        ("A", "volunteered at the shelter today", 0),
        ("B", "that's awesome, how was it", 0),
        ("A", "great, but the kitchen was so hot from the ovens", 0),
        ("B", "we should sign up together next time", 0),
    ],
}
